title: Chancellor Cynthia K. Larive
email: chancellor@ucsc.edu
description: >- # this means to ignore newlines until "baseurl:"
  Cynthia K. Larive is the eleventh Chancellor of University of California Santa Cruz. Chancellor Larive’s career has been marked by her commitment to student success, inclusion and equity.
url: "https://chancellor.ucsc.edu"
timezone: "America/Los_Angeles"

source: ./_src
destination: ./_site

# Build settings
markdown: kramdown
permalink: /communications/:year/:month/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections_dir: collections
collections:
  announcements:
    label: "announcements"
    output: true
  links:
    label: "links"
    output: false
  posts:
    label: "posts"
    output: true

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/cl-web.jpg
  - scope:
      path: ""
      type: "posts"
    values:
      related:
        - title: "Messages to campus"
          url: "/communications/"
        - title: "Campus News"
          url: "https://news.ucsc.edu"
        - title: "UC Santa Cruz home page"
          url: "https://www.ucsc.edu"
