[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' *.ucsc.edu; img-src 'self' *.ucsc.edu www.google-analytics.com data:; script-src 'self' 'unsafe-inline' *.ucsc.edu www.google-analytics.com ajax.googleapis.com *.google.com *.googletagmanager.com use.fontawesome.com; style-src 'self' 'unsafe-inline' *.ucsc.edu *.googleapis.com unpkg.com; font-src 'self' fonts.gstatic.com; frame-src 'self' *.youtube.com; object-src 'none';"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "DENY"
[[redirects]]
  from = "https://chancellor.ucsc.edu/campus-reaction/"
  to = "https://news.ucsc.edu/2019/05/larive-reaction.html"
  status = 301
  force = true
[[redirects]]
  from = "https://leadership.ucsc.edu/*"
  to = "https://chancellor.ucsc.edu/:splat"
  status = 301
  force = true
